name: simple_movie_tv_shows_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/png/

fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf